[program:seaweedfs]
command=/usr/bin/weed server -dir=/var/lib/seaweedfs -s3
autostart=%(ENV_ENABLE_BROKER)s
autorestart=true
startsecs=5
stdout_logfile=/var/log/%(program_name)s.log
redirect_stderr=true
