[program:setup-kafka-connect]
command=/usr/local/bin/setup-kafka-connect.sh
environment=KAFKA_CONNECT_TOPIC="%(ENV_KAFKA_CONNECT_TOPIC)s",SEAWEEDFS_BUCKET="%(ENV_SEAWEEDFS_BUCKET)s"
autostart=%(ENV_ENABLE_BROKER)s
autorestart=false
startsecs=0
exitcodes=0
stdout_logfile=/var/log/%(program_name)s.log
redirect_stderr=true
