[program:setup-seaweedfs]
command=/usr/local/bin/setup-seaweedfs.sh
environment=SEAWEEDFS_BUCKET="%(ENV_SEAWEEDFS_BUCKET)s"
autostart=%(ENV_ENABLE_BROKER)s
autorestart=false
startsecs=0
exitcodes=0
stdout_logfile=/var/log/%(program_name)s.log
redirect_stderr=true
